Repository kozaka93/2024L-ExploratoryDataAnalysis, pull requests merged in 2024-06, with the labels that each got.

#393 [HW6] Ryll Mikolaj
  homeworks/hw6/RyllMikolaj/cleaned.csv
  homeworks/hw6/RyllMikolaj/pd6.ipynb
Labels: HW 6

#392 [HW6] SienMagdalena
  homeworks/hw6/SienMagdalena/HW6.ipynb
Labels: HW 6

#391 [HW6] Podbielski Bruno
  homeworks/hw6/PodbielskiBruno/HW6.ipynb
  homeworks/hw6/PodbielskiBruno/cleaned.csv
Labels: HW 6

#390 [HW6] Gromada Patrycja
  homeworks/hw6/GromadaPatrycja/[HW6] Patrycja Gromada.ipynb
Labels: HW 6

#386 LipinskaMalgorzata[HW6]
  homeworks/hw6/LipinskaMalgorzata/LipinskaMalgorzata.ipynb
Labels: fixes needed 🛠️, HW 6

#385 [HW6] Tabian Maksymilian
  homeworks/hw6/TabianMaksymilian/World-happiness-report-2024.csv
  homeworks/hw6/TabianMaksymilian/hw6.ipynb
Labels: HW 6

#383 [HW6] Kapciak Lukasz
  homeworks/hw6/KapciakLukasz/HW6.ipynb
Labels: HW 6

#382 [HW6] Orzechowska Weronika
  homeworks/hw6/OrzechowskaWeronika/HW6.ipynb
Labels: HW 6

#381 [HW6] Gajda Natalia
  homeworks/hw6/GajdaNatalia/ [HW6] Gajda Natalia.ipynb
Labels: HW 6

#380 [HW6] Kowalski Paweł
  homeworks/hw6/KowalskiPawel/HW6.ipynb
Labels: HW 6

#379 [HW6] Bartosiewicz Piotr
  homeworks/hw6/BartosiewiczPiotr/piotr_bartosiewicz_hw6.ipynb
Labels: HW 6

#378 [HW6] Krzyzanowski Adrian
  homeworks/hw6/KrzyzanowskiAdrian/HW6.ipynb
Labels: HW 6

#377 [HW6] Zebialowicz Alicja
  homeworks/hw6/ZebialowiczAlicja/HW6.ipynb
  homeworks/hw6/ZebialowiczAlicja/energy_dataset_.csv
Labels: HW 6

#376 [HW6] Strzelczyk Julia
  homeworks/hw6/StrzelczykJulia/hw6_wded.ipynb
Labels: HW 6

#375 [HW6] Maciej Koczorowski
  homeworks/hw6/KoczorowskiMaciej/PD6.ipynb
Labels: HW 6

#374 [HW6] Karch Aleksander
  homeworks/hw6/KarchAleksander/AnalizawPythonie.ipynb
Labels: HW 6

#372 [HW6] Ovcharenko Oleksandra
  homeworks/hw6/OvcharenkoOleksandra/HW6.ipynb
Labels: HW 6

#371 [HW6] Wyszomierski Lukasz
  homeworks/hw6/WyszomierskiLukasz/HW6.ipynb
Labels: HW 6

#370 [HW6] Szymanski Bartosz
  homeworks/hw6/SzymanskiBartosz/HW6 WDEP.ipynb
  homeworks/hw6/SzymanskiBartosz/World-happiness-report-2024.csv
Labels: HW 6

#369 [HW6] Maczka Marek
  homeworks/hw6/MaczkaMarek/World-happiness-report-updated_2024.csv
  homeworks/hw6/MaczkaMarek/[HW6] Maczka Marek.ipynb
Labels: HW 6

#367 [HW6] CholewinskiKacper
  homeworks/hw6/CholewinskiKacper/HW6.html
  homeworks/hw6/CholewinskiKacper/HW6.ipynb
  homeworks/hw6/CholewinskiKacper/cleaned.csv
Labels: HW 6

#366 [HW6] Brochocki Mateusz
  homeworks/hw6/BrochockiMateusz/World-happiness-report-2024.csv
  homeworks/hw6/BrochockiMateusz/[HW6]BrochockiMateusz.ipynb
Labels: HW 6

#365 [HW6] Luczkiewicz Izabela
  homeworks/hw6/LuczkiewiczIzabela/HW6.ipynb
Labels: HW 6

#364 [HW6] Dębski Michał
  homeworks/hw6/DebskiMichal/[HW6]DebskiMichal.ipynb
  homeworks/hw6/DebskiMichal/energy_dataset_.csv
Labels: HW 6

#363 [HW6] Pres Ewelina
  homeworks/hw6/PresEwelina/data/energy_dataset_.csv
  homeworks/hw6/PresEwelina/eda_renewable_energy.ipynb
Labels: HW 6

#402 [projekt2] Debski_Koczorowski_Luczkiewicz
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/ISO_codes.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_0.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_15.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_18.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_25.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_50.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_65.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi__wiek_na_mln_total.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi_wypadki.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi_wypadki_autostrada.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi_wypadki_miejskie.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi_wypadki_nieznane.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi_wypadki_wiejskie.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/drogi_wypadki_wiek_na_mln.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/tran_sf_railsu$defaultview_spreadsheet.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Dane/tran_sf_railvi__custom_11230338_spreadsheet.xlsx
  projects/project2/Debski_Koczorowski_Luczkiewicz/Kody/app_new.r
  projects/project2/Debski_Koczorowski_Luczkiewicz/README.md
  projects/project2/Debski_Koczorowski_Luczkiewicz/obrazki/apka_1.png
  projects/project2/Debski_Koczorowski_Luczkiewicz/obrazki/apka_2.png
  projects/project2/Debski_Koczorowski_Luczkiewicz/obrazki/apka_3.png
Labels: Project 2

#404 [projekt2] Idczak_Tabian_Wojtkowiak
  projects/project2/Idczak_Tabian_Wojtkowiak/README.md
  projects/project2/Idczak_Tabian_Wojtkowiak/kody/app2.R
  projects/project2/Idczak_Tabian_Wojtkowiak/zdjecia/app-screen-1.png
  projects/project2/Idczak_Tabian_Wojtkowiak/zdjecia/app-screen-2.png
  projects/project2/Idczak_Tabian_Wojtkowiak/zdjecia/app-screen-3.png
Labels: Project 2

#415 [projekt2] Balcerzak_Karch_Krzyzanowski
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/INV.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/MTN.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/PASSENGER_TRANSPORT.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/co-emissions-by-sector.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/greenhouse-gas-emissions-from-transport-7.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/passengers.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Dane/specific-co2-emissions-per-tonne-2.csv
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/Kod/copy_of_a.r
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/README.md
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/obrazki/221.png
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/obrazki/222.png
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/obrazki/223.png
  projects/project2/[projekt2] Balcerzak_Karch_Krzyzanowski/obrazki/224.png
Labels: Project 2

#421 [projekt2] Baginski_Brochocki_Wolczyk
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Liczba_zatrzyman_I_-_XII_2023.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Liczba_zatrzyman_pociagow_na_stacjach_w_2022.csv
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Liczba_zatrzyman_pociagow_na_stacjach_w_2022.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Pomocnicze2021.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Punktualnosc_pasazerska_2023_III_kwartal.csv
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Sredni_czas_opoznien_na_stacjach_dla_pociagow_opoznionych_powyzej_5_minut2021.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Wskaznik2022.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Wskaznik2023.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/Wymiana_pasazerska_2021_-_akt__ranking.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/miscelanneous_db.csv
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/nawoj.xlsx
  projects/project2/Baginski_Brochocki_Wolczyk/Dane/polska-wojewodztwa.geojson
  projects/project2/Baginski_Brochocki_Wolczyk/Kody/projekt.r
  projects/project2/Baginski_Brochocki_Wolczyk/README.md
  projects/project2/Baginski_Brochocki_Wolczyk/Screeny/Zrzut1.png
  projects/project2/Baginski_Brochocki_Wolczyk/Screeny/Zrzut2.png
  projects/project2/Baginski_Brochocki_Wolczyk/Screeny/Zrzut3.png
  projects/project2/Baginski_Brochocki_Wolczyk/Screeny/Zrzut4.png
Labels: Project 2
