Repository kozaka93/2024L-ExploratoryDataAnalysis, pull requests merged in 2024-05, with the labels that each got.

#307 [HW4] Maciej Koczorowski
  homeworks/hw4/KoczorowskiMaciej/PD4.Rmd
  homeworks/hw4/KoczorowskiMaciej/PD4.html
  homeworks/hw4/KoczorowskiMaciej/chipotle_stores.csv
Labels: HW 4

#304 [HW4] Serkuczewski Michał
  homeworks/hw4/SerkuczewskiMichal/FastFoodRestaurants.csv
  homeworks/hw4/SerkuczewskiMichal/HW4.Rproj
  homeworks/hw4/SerkuczewskiMichal/HW4_explo.pdf
  homeworks/hw4/SerkuczewskiMichal/skrypt.R
Labels: HW 4

#301 [HW4] Markowski Piotr
  homeworks/hw4/MarkowskiPiotr/HW4.R
  homeworks/hw4/MarkowskiPiotr/Piotr Markowski_raport.pdf
Labels: HW 4

#300 [HW 4] Szymanski Bartosz
  homeworks/hw4/SzymanskiBartosz/exceldane.xlsx
  homeworks/hw4/SzymanskiBartosz/nowyraport (1).html
  homeworks/hw4/SzymanskiBartosz/nowyraport.Rmd
Labels: HW 4

#299 [HW4] Gajda Natalia
  homeworks/hw4/GajdaNatalia/GajdaNataliaHW4.R
  homeworks/hw4/GajdaNatalia/covid_usa.html
  homeworks/hw4/GajdaNatalia/covidcases.html
  homeworks/hw4/GajdaNatalia/coviddeaths.html
Labels: HW 4

#298 [HW4] Lechoszest Igor
  homeworks/hw4/LechoszestIgor/PD4.R
  homeworks/hw4/LechoszestIgor/PD4.pdf
Labels: HW 4

#297 [HW4} Kowalski Paweł
  homeworks/hw4/KowalskiPawel/HW4.pdf
  homeworks/hw4/KowalskiPawel/PD4.R
Labels: HW 4

#295 [HW4]PokropekDaniel
  homeworks/hw4/PokropekDaniel/Trzcina cukrowa - wizualizacja.R
  homeworks/hw4/PokropekDaniel/Trzcina cukrowa - wizualizacja.Rmd
  homeworks/hw4/PokropekDaniel/Trzcina-cukrowa---wizualizacja.pdf
Labels: HW 4

#293 [HW4] Lipińska Małgorzata
  homeworks/hw4/LipinskaMalgorzata/HW4_ML.R
  homeworks/hw4/LipinskaMalgorzata/Praca domowa 4.pdf
Labels: HW 4

#292 [HW4] Podbielski Bruno
  homeworks/hw4/PodbielskiBruno/HW4 raport.Rmd
  homeworks/hw4/PodbielskiBruno/HW4-raport.html
  homeworks/hw4/PodbielskiBruno/HW4.R
  homeworks/hw4/PodbielskiBruno/elektrownie.html
  homeworks/hw4/PodbielskiBruno/power_plants.csv
Labels: HW 4

#289 [HW4] Pokora Bartosz
  homeworks/hw4/PokoraBartosz/Netflix subscription fee Dec-2021.csv
  homeworks/hw4/PokoraBartosz/PD4_Kod.Rmd
  homeworks/hw4/PokoraBartosz/PD4_Raport.html
  homeworks/hw4/PokoraBartosz/countries.geo.json
  homeworks/hw4/PokoraBartosz/gdp-per-capita-world-bank-constant-usd.csv
Labels: HW 4

#288 Wojciechowski Maksymilian
  homeworks/hw4/WojciechowskiMaksymilian/Raport.Rmd
  homeworks/hw4/WojciechowskiMaksymilian/Raport.html
  homeworks/hw4/WojciechowskiMaksymilian/terrorists/README.txt
  homeworks/hw4/WojciechowskiMaksymilian/terrorists/terrorist_groups.txt
  homeworks/hw4/WojciechowskiMaksymilian/terrorists/terrorist_names.txt
  homeworks/hw4/WojciechowskiMaksymilian/terrorists/terrorist_pairs.txt
Labels: HW 4

#286 [HW4] Idczak Aleksandra
  homeworks/hw4/IdczakAleksandra/HW4.Rmd
  homeworks/hw4/IdczakAleksandra/HW4.html
Labels: HW 4

#285 [HW4] Uznańska Aleksandra
  homeworks/hw4/UznanskaAleksandra/Animal_dataset.csv
  homeworks/hw4/UznanskaAleksandra/HW4.Rproj
  homeworks/hw4/UznanskaAleksandra/HW4.pdf
  homeworks/hw4/UznanskaAleksandra/PD4.R
Labels: HW 4

#284 [HW4] Karch Aleksander
  homeworks/hw4/KarchAleksander/hw4.Rmd
  homeworks/hw4/KarchAleksander/hw4.pdf
Labels: HW 4

#283 [HW4] Guttman Jan
  homeworks/hw4/GuttmanJan/[HW4]GuttmanJan_graf.png
  homeworks/hw4/GuttmanJan/[HW4]GuttmanJan_raport.Rmd
  homeworks/hw4/GuttmanJan/[HW4]GuttmanJan_raport.pdf
Labels: HW 4

#281 [HW4] Izabela Luczkiewicz
  homeworks/hw4/LuczkiewiczIzabela/HW4.Rmd
  homeworks/hw4/LuczkiewiczIzabela/HW4.html
Labels: HW 4

#279 [HW4] Strzelczyk Julia
  homeworks/hw4/StrzelczykJulia/map_forests.R
  homeworks/hw4/StrzelczykJulia/raport_pd4.html
Labels: HW 4

#278 [HW4] Lipowski Jedrzej
  homeworks/hw4/LipowskiJedrzej/HW4.R
  homeworks/hw4/LipowskiJedrzej/Raport.html
  homeworks/hw4/LipowskiJedrzej/europe.json
  homeworks/hw4/LipowskiJedrzej/foreign.csv
Labels: HW 4

#277 [HW4] Gromada Patrycja
  homeworks/hw4/GromadaPatrycja/HW4_PG.Rmd
  homeworks/hw4/GromadaPatrycja/README.md
Labels: HW 4

#275 [HW4] Ryll Mikolaj
  homeworks/hw4/RyllMikolaj/HM4.Rmd
  homeworks/hw4/RyllMikolaj/HM4.pdf
  homeworks/hw4/RyllMikolaj/student_cooperation.gml
Labels: HW 4

#274 [HW4] Baginski Kacper
  homeworks/hw4/BaginskiKacper/custom.geo.json
  homeworks/hw4/BaginskiKacper/homicide_data.csv
  homeworks/hw4/BaginskiKacper/interactive_map.html
  homeworks/hw4/BaginskiKacper/map_code.R
  homeworks/hw4/BaginskiKacper/raport.Rmd
  homeworks/hw4/BaginskiKacper/raport.html
Labels: HW 4

#273 [HW4] Cholewinski Kacper
  homeworks/hw4/CholewinskiKacper/HW4.Rmd
  homeworks/hw4/CholewinskiKacper/HW4.html
Labels: HW 4

#271 [HW4] Ovcharenko Oleksandra
  homeworks/hw4/OvcharenkoOleksandra/HW4.Rmd
  homeworks/hw4/OvcharenkoOleksandra/HW4.html
Labels: HW 4

#270 [HW 4] Maczka Marek
  homeworks/hw4/MaczkaMarek/Building_Violations_small.csv
  homeworks/hw4/MaczkaMarek/HW_4_kod.R
  homeworks/hw4/MaczkaMarek/HW_4_raport.Rmd
  homeworks/hw4/MaczkaMarek/HW_4_raport.html
  homeworks/hw4/MaczkaMarek/leaflet.html
Labels: HW 4

#268 [HW4]Wolczyk_Michal
  homeworks/hw4/Wolczyk_Michal/eksploracja.pdf
  homeworks/hw4/Wolczyk_Michal/praca_domowa.R
Labels: HW 4

#265 [HW4] Zebialowicz Alicja
  homeworks/hw4/ZebialowiczAlicja/HW4.Rmd
  homeworks/hw4/ZebialowiczAlicja/HW4.html
Labels: HW 4

#263 [HW4] Turczyński Maciej
  homeworks/hw4/TurczynskiMaciej/Praca_domowa_4_eksploracja.pdf
  homeworks/hw4/TurczynskiMaciej/US_elections.R
  homeworks/hw4/TurczynskiMaciej/US_plot.jpeg
Labels: HW 4

#311 [HW4] Wojtkowiak Oliwia
  homeworks/hw4/WojtkowiakOliwia/HW4_Wojtkowiak_Oliwia.Rmd
  homeworks/hw4/WojtkowiakOliwia/_HW4_raport (1).pdf
Labels: fixes needed 🛠️, HW 4

#267 [HW4] Bartosiewicz Piotr
  homeworks/hw4/BartosiewiczPiotr/HW4_Raport.html
  homeworks/hw4/BartosiewiczPiotr/Piotr_Bartosiewicz_hw4.Rmd
Labels: fixes needed 🛠️, HW 4

#312 [HW5] Franciszek Salinski
  homeworks/hw5/SalinskiFranciszek/hw5.html
  homeworks/hw5/SalinskiFranciszek/hw5.ipynb
  homeworks/hw5/SalinskiFranciszek/image.png
Labels: HW 5

#321 [HW5] Turczyński Maciej
  homeworks/hw5/TurczynskiMaciej/Raport HW5.Rmd
  homeworks/hw5/TurczynskiMaciej/slaba_wizualizacja.png
Labels: HW 5

#326 [HW5] Serkuczewski Michał
  homeworks/hw5/SerkuczewskiMichal/HW5.pdf
  homeworks/hw5/SerkuczewskiMichal/app.png
  homeworks/hw5/SerkuczewskiMichal/dane.png
  homeworks/hw5/SerkuczewskiMichal/kobiety.png
  homeworks/hw5/SerkuczewskiMichal/mezczyzni.png
  homeworks/hw5/SerkuczewskiMichal/obie.png
  homeworks/hw5/SerkuczewskiMichal/skrypt.R
Labels: HW 5

#340 [HW5] Galat Julia
  homeworks/hw5/[HW5]GalatJulia/[HW5]GalatJulia.Rmd
Labels: HW 5

#342 [HW5] Kowalski Paweł
  homeworks/hw5/KowalskiPawel/HW5.R
  homeworks/hw5/KowalskiPawel/nowy_wykres.html
  homeworks/hw5/KowalskiPawel/zły_wykres.jpg
Labels: HW 5

#343 [HW5] Gajda Natalia
  homeworks/hw5/GajdaNatalia/BadPlot.png
  homeworks/hw5/GajdaNatalia/HW5.R
  homeworks/hw5/GajdaNatalia/NYCRobbery.html
Labels: HW 5

#354 [HW5] Wolczyk Michal
  homeworks/hw5/WolczykMichal/PD (1).pdf
  homeworks/hw5/WolczykMichal/app.R
Labels: HW 5

#350 [HW5] Lipińska Małgorzata
  homeworks/hw5/Lipińska Małgorzata/LipińskaMałgorzata/Raport.pdf
  homeworks/hw5/Lipińska Małgorzata/LipińskaMałgorzata/app.R
  homeworks/hw5/Lipińska Małgorzata/Raport.pdf
  homeworks/hw5/Lipińska Małgorzata/app.R
Labels: HW 5
