Repository kozaka93/2024L-ExploratoryDataAnalysis, pull requests merged in 2024-04, with the labels that each got.

#236 [HW3] Cholewiński Kacper
  homeworks/hw3/CholewinskiKacper/HW3.pdf
Labels: HW 3

#235 [PD3] Gromada Patrycja
  homeworks/hw3/GromadaPatrycja/HW3_PatrycjaGromada.pdf
Labels: HW 3

#233 [HW3] Krawczyk_Maria
  homeworks/hw3/KrawczykMaria/HW3.pdf
Labels: HW 3

#232 [HW3] ZajacKarolina
  homeworks/hw3/ZajacKarolina/20240315_Informacja_za_luty_2024.pdf
  homeworks/hw3/ZajacKarolina/dobry_wykres.jpeg
  homeworks/hw3/ZajacKarolina/fatalny_wykres.R
  homeworks/hw3/ZajacKarolina/raport.pdf
Labels: HW 3

#230 [HW3] Orzechowska Weronika
  homeworks/hw3/OrzechowskaWeronika/HW3.pdf
Labels: HW 3

#229 [HW3] Lechoszest Igor
  homeworks/hw3/LechoszestIgor/IgorLechoszest.pdf
Labels: HW 3

#228 [HW3} Markowski Piotr
  homeworks/hw3/MarkowskiPiotr/kod.R
  homeworks/hw3/MarkowskiPiotr/opis.pdf
Labels: HW 3

#226 [HW3] Krawiec Krzysztof
  homeworks/hw3/KrawiecKrzysztof/HW3 Krawiec Krzysztof.pdf
  homeworks/hw3/KrawiecKrzysztof/HW3.R
Labels: HW 3

#224 [HW3] Podbielski Bruno
  homeworks/hw3/PodbielskiBruno/HW3.R
  homeworks/hw3/PodbielskiBruno/HW3.pdf
Labels: HW 3

#223 [HW3] Lipińska Małgorzata
  homeworks/hw3/LipinskaMalgorzata/HW3 kod.R
  homeworks/hw3/LipinskaMalgorzata/LipinskaMalgorzata.pdf
Labels: HW 3

#222 [HW3] Kiszka Mateusz
  homeworks/hw3/KiszkaMateusz/HW3_Kiszka_Mateusz.pdf
Labels: HW 3

#221 [HW3] Maciej Koczorowski
  homeworks/hw3/KoczorowskiMaciej/HW3.pdf
Labels: HW 3

#220 [HW3] Baginski Kacper
  homeworks/hw3/BaginskiKacper/Moj wykres - kod.R
  homeworks/hw3/BaginskiKacper/Moj wykres.png
  homeworks/hw3/BaginskiKacper/Oryginalny wykres.png
  homeworks/hw3/BaginskiKacper/Porownanie.Rmd
  homeworks/hw3/BaginskiKacper/Porownanie.pdf
Labels: HW 3

#219 [HW3] Wyszomierski Lukasz
  homeworks/hw3/WyszomierskiLukasz/Raport_pd3.pdf
Labels: HW 3

#218 [PD3] Krzysztof Maslak
  homeworks/hw3/MaslakKrzysztof/[HW3] Maślak Krzysztof.pdf
Labels: HW 3

#217 [HW3] Le Bihan Julia
  homeworks/hw3/LeBihanJulia/poprawiony_wykres.pdf
Labels: HW 3

#216 [HW3] WojciechowksiMaksymilian
  homeworks/hw3/WojciechowskiMaksymilian/Pd3.pdf
Labels: HW 3

#215 [HW3] Serkuczewski Michał
  homeworks/hw3/SerkuczewskiMichal/HW3.pdf
Labels: HW 3

#234 [HW3] Pokora Bartosz
  homeworks/hw3/PokoraBartosz/Praca domowa 3.pdf
Labels: HW 3

#210 [HW3] Balcerzak Marta
  homeworks/hw3/BalcerzakMarta/hw3.html
Labels: HW 3

#214 [HW3] Gajda Natalia
  homeworks/hw3/GajdaNatalia/HW3.pdf
Labels: HW 3

#206 [HW3] Uznańska Aleksandra
  homeworks/hw3/UznanskaAleksandra/HW3.pdf
Labels: HW 3

#205 [HW3] Szymanski Bartosz
  homeworks/hw3/SzymanskiBartosz/SzymanskiBartoszHW3.pdf
Labels: HW 3

#204 [HW3] Maczka Marek
  homeworks/hw3/MaczkaMarek/[HW3] Maczka Marek.pdf
Labels: HW 3

#202 [HW3] Zebialowicz Alicja
  homeworks/hw3/ZebialowiczAlicja/[HW3]ZebialowiczAlicja.pdf
Labels: HW 3

#200 [HW3] Bartosiewicz Piotr
  homeworks/hw3/BartosiewiczPiotr/raport_Piotr_Bartosiewicz.html
Labels: HW 3

#199 [HW3] Ryll Mikolaj
  homeworks/hw3/RyllMikolaj/HM3.html
Labels: HW 3

#196 [HW3]Wojtkowiak Oliwia
  homeworks/hw3/WojtkowiakOliwia/HW3_Wojtkowiak_Oliwia.pdf
  homeworks/hw3/WojtkowiakOliwia/poprawa wykresu.R
Labels: HW 3

#194 [HW3] Krzyzanowski Adrian
  homeworks/hw3/KrzyzanowskiAdrian/HW3.pdf
Labels: HW 3

#192 [HW3] Guttman Jan
  homeworks/hw3/GuttmanJan/[HW3]GuttmanJan.html
Labels: HW 3

#191 [HW3] Pres Ewelina
  homeworks/hw3/PresEwelina/PD3.pdf
  homeworks/hw3/PresEwelina/pd3.r
Labels: HW 3

#190 HW3 Sien Magdalena
  homeworks/hw3/SienMagdalena/HW3.pdf
Labels: HW 3

#183 [HW3] Brochocki Mateusz
  homeworks/hw3/BrochockiMateusz/[HW3]BrochockiMateusz.html
Labels: HW 3

#182 [HW3] Lipowski Jedrzej
  homeworks/hw3/LipowskiJedrzej/HW.3.html
Labels: HW 3

#195 [HW3] MichnaJakub
  homeworks/hw3/MichnaJakub/Raport.pdf
  homeworks/hw3/MichnaJakub/kod.R
Labels: HW 3

#198 [HW3] Wolczyk Michal
  homeworks/hw3/WolczykMichal/HW_3.R
  homeworks/hw3/WolczykMichal/Hw.html
Labels: fixes needed 🛠️, HW 3

#247 [projekt1] Uznanska_Turczynski_Wojciechowski
  projects/project1/Uznanska_Turczynski_Wojciechowski/README.md
  projects/project1/Uznanska_Turczynski_Wojciechowski/Uznanska_Turczynski_Wojciechowski.pdf
  projects/project1/Uznanska_Turczynski_Wojciechowski/Uznanska_Turczynski_Wojciechowski.png
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/Game_of_Thrones_Script.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/all_books.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/book1.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/book2.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/book3.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/book4.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/book45.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/book5.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/character_gender.json
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/code_to_all_plots.R
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/deaths.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/odcinki.csv
  projects/project1/Uznanska_Turczynski_Wojciechowski/kody/wszystkie_postacie.csv
Labels: Project 1

#244 [projekt1] Brochocki_Debski_Karch
  projects/project1/brochocki_debski_karch/README.md
  projects/project1/brochocki_debski_karch/brochocki_debski_karch.pdf
  projects/project1/brochocki_debski_karch/brochocki_debski_karch.png
  projects/project1/brochocki_debski_karch/kody/Bond_cars&trucks.xlsx
  projects/project1/brochocki_debski_karch/kody/Bond_filmy.xlsx
  projects/project1/brochocki_debski_karch/kody/Bond_kobiety.xlsx
  projects/project1/brochocki_debski_karch/kody/Bond_location.xlsx
  projects/project1/brochocki_debski_karch/kody/Bond_music.csv
  projects/project1/brochocki_debski_karch/kody/Bond_rotten_tomatoes.xlsx
  projects/project1/brochocki_debski_karch/kody/Bond_time.csv
  projects/project1/brochocki_debski_karch/kody/Bond_time.xlsx
  projects/project1/brochocki_debski_karch/kody/James_Bond_movie_body_counts.xlsx
  projects/project1/brochocki_debski_karch/kody/[projekt1] Brochocki_Debski_Karch.rmd
  projects/project1/brochocki_debski_karch/kody/bondactorbox.csv
  projects/project1/brochocki_debski_karch/kody/bondgirlfilm.csv
Labels: Project 1

#248 [projekt1] Krzyzanowski_Lipinski_Ryll
  projects/project1/Krzyzanowski_Lipinski_Ryll/Krzyzanowski_Lipinski_Ryll.pdf
  projects/project1/Krzyzanowski_Lipinski_Ryll/Krzyzanowski_Lipinski_Ryll.png
  projects/project1/Krzyzanowski_Lipinski_Ryll/README.md
  projects/project1/Krzyzanowski_Lipinski_Ryll/kody/Projekt FILM.R
  projects/project1/Krzyzanowski_Lipinski_Ryll/kody/boxplot.r
  projects/project1/Krzyzanowski_Lipinski_Ryll/kody/prequel_sequel.R
Labels: Project 1

#257 [projekt1] Cholewinski_Szymanski_Tabian
  projects/project1/Cholewinski_Szymanski_Tabian/Cholewinski_Szymanski_Tabian.pdf
  projects/project1/Cholewinski_Szymanski_Tabian/Cholewinski_Szymanski_Tabian.png
  projects/project1/Cholewinski_Szymanski_Tabian/README.md
  projects/project1/Cholewinski_Szymanski_Tabian/kody/pr.r
  projects/project1/Cholewinski_Szymanski_Tabian/kody/revenues.r
  projects/project1/Cholewinski_Szymanski_Tabian/kody/world_map.R
Labels: Project 1

#258 [projekt1] Orzechowska_Krawiec_Bartosiewicz
  projects/project1/Orzechowska_Krawiec_Bartosiewicz/Orzechowska_Krawiec_Bartosiewicz.pdf
  projects/project1/Orzechowska_Krawiec_Bartosiewicz/README/README.txt
  projects/project1/Orzechowska_Krawiec_Bartosiewicz/kody/kody.R
Labels: Project 1
