Repository kozaka93/2024L-ExploratoryDataAnalysis, pull requests merged in 2024-03, with the labels that each got.

#64 [HW0] BartosiewiczPiotr
  homeworks/hw0/BartosiewiczPiotr/[HW0]BartosiewiczPiotr.R
Labels: HW0

#121 Add files via upload
  homeworks/hw1/MichnaJakub/MichnaJakub.R
Labels: HW 1

#120 MarkowskiPiotr
  homeworks/hw1/MarkowskiPiotr/HW1.R
Labels: HW 1

#119 [HW1] Orzechowska Weronika
  homeworks/hw1/OrzechowskaWeronika/HW1.R
Labels: HW 1

#118 [HW1] Maślak Krzysztof
  homeworks/hw1/MaslakKrzysztof/MaslakKrzysztofPD1.R
Labels: HW 1

#117 [HW1] ZajacKarolina
  homeworks/hw1/ZajacKarolina/HW1.R
Labels: HW 1

#116 [HW1] Kapciak Lukasz
  homeworks/hw1/KapciakLukasz/HW1.r
Labels: HW 1

#115 [HW1]PodgórskiMateusz
  homeworks/hw1/PodgorskiMateusz/HW1 zrobione.R
Labels: HW 1

#114 [HW1] Gajda Natalia
  homeworks/hw1/GajdaNatalia/HW1.R
Labels: HW 1

#113 [HW1] Kiszka Mateusz
  homeworks/hw1/KiszkaMateusz/HW1.R
Labels: HW 1

#112 [HW1] Le Bihan Julia
  homeworks/hw1/LeBihanJulia/HW1.R
Labels: HW 1

#111 [HW1] Podbielski Bruno
  homeworks/hw1/PodbielskiBruno/HW1.R
Labels: HW 1

#110 [PD1] Maksymilian Tabian
  homeworks/hw1/TabianMaksymilian/HW1.R
Labels: HW 1

#109 [HW1] Lipowski Jedrzej
  homeworks/hw1/LipowskiJedrzej/HW1.R
Labels: HW 1

#107 Wojciechowski Maksymilian Pd1
  homeworks/hw1/WojciechowskiMaksymilian/HW1.R
Labels: HW 1

#106 [HW1] Saliński Franciszek
  homeworks/hw1/SalinskiFranciszek/HW1.R
Labels: HW 1

#105 [HW1]LipinskaMalgorzata
  homeworks/hw1/LipinskaMalgorzata/HW1.R
Labels: HW 1

#104 [HW1] Mikołaj Ryll
  homeworks/hw1/RyllMikolaj/HW1.R
Labels: HW 1

#103 [HW1] Pokora Bartosz
  homeworks/hw1/PokoraBartosz/HW1.R
Labels: HW 1

#102 [HW1] Krawczyk Maria
  homeworks/hw1/KrawczykMaria/HW1.R
Labels: HW 1

#100 [PD1] Maczka Marek
  homeworks/hw1/MaczkaMarek/[HW1] Maczka Marek.R
Labels: HW 1

#99 [HW1] Kowalski Paweł
  homeworks/hw1/KowalskiPawel/PD1.R
Labels: HW 1

#98 [PD1] Patrycja Gromada
  homeworks/hw1/GromadaPatrycja/HW1 PG.R
Labels: HW 1

#97 [HW1]WołczykMichał
  homeworks/hw1/WolczykMichal/HW1.R
Labels: HW 1

#96 [HW1] Strzelczyk Julia
  homeworks/hw1/StrzelczykJulia/HW1.R
Labels: HW 1

#95 [HW0] KrawiecKrzysztof
  homeworks/hw0/KrawiecKrzysztof/proton.R
  homeworks/hw1/KrawiecKrzysztof/[HW1] KrawiecKrzysztof.R
Labels: HW 1

#94 [HW1] Pres Ewelina
  homeworks/hw1/PresEwelina/HW1.R
Labels: HW 1

#93 [PD1] Wyszomierski Lukasz
  homeworks/hw1/WyszomierskiLukasz/HW1.R
Labels: HW 1

#92 [PD1] Cholewiński Kacper
  homeworks/hw1/CholewinskiKacper/HW1.R
Labels: HW 1

#91 [HW1] Szymanski Bartosz
  homeworks/hw1/SzymanskiBartosz/HW1.R
Labels: HW 1

#90 [HW1] Idczak Aleksandra
  homeworks/hw1/IdczakAleksandra/HW1.R
Labels: HW 1

#89 [HW1] Zebialowicz Alicja
  homeworks/hw1/ZebialowiczAlicja/[HW1]ZebialowiczAlicja.R
Labels: HW 1

#88 [PD1] Balcerzak Marta
  homeworks/hw1/BalcerzakMarta/pd1.R
Labels: HW 1

#87 [HW1] Ovcharenko Oleksandra
  homeworks/hw1/OvcharenkoOleksandra/HW1.R
Labels: HW 1

#86 [HW1] Krzyzanowski Adrian
  homeworks/hw1/KrzyzanowskiAdrian/HW1.R
Labels: HW 1

#85 [HW1] Galat Julia
  homeworks/hw1/GalatJulia/[HW1] Gałat Julia.R
Labels: HW 1

#84 [HW1] Baginski Kacper
  homeworks/hw1/BaginskiKacper/[HW1] Baginski Kacper.R
Labels: HW 1

#83 [HW1] Wojtkowiak Oliwia
  homeworks/hw1/WojtkowiakOliwia/HW1_Oliwia_Wojtkowiak.R
Labels: HW 1

#80 [HW1] Guttman Jan
  homeworks/hw1/GuttmanJan/[HW1]GuttmanJan.R
Labels: HW 1

#79 [HW1] Turczynski Maciej
  homeworks/hw1/TurczynskiMaciej/HW1.r
Labels: HW 1

#78 [HW1] Lechoszest Igor
  homeworks/hw1/LechoszestIgor/HW1.R
Labels: HW 1

#77 [HW1] Bartosiewicz Piotr
  homeworks/hw1/BartosiewiczPiotr/[HW1]BartosiewiczPiotr.R
Labels: HW 1

#76 [HW1] Łuczkiewicz Izabela
  homeworks/hw1/LuczkiewiczIzabela/HW1.R
Labels: HW 1

#74 [HW1] Sien Magdalena
  homeworks/hw0/SienMagdalena/proton_solve.R
  homeworks/hw1/SienMagdalena/HW1.R
Labels: HW 1

#73 [HW1] Debski Michal
  homeworks/hw1/DebskiMichal/[HW1] Debski Michal.R
Labels: HW 1

#72 [HW1] Koczorowski Maciej
  homeworks/hw1/KoczorowskiMaciej/HW1.R
Labels: HW 1

#69 [HW1] Brochocki Mateusz
  homeworks/hw1/BrochockiMateusz/[HW1]BrochockiMateusz.R
Labels: HW 1

#68 [HW1] Karch Aleksander
  homeworks/hw1/KarchAleksander/HW1.R
  homeworks/hw1/KarchAleksander/data.csv
Labels: HW 1

#63 [HW1] Serkuczewski Michał
  homeworks/hw1/SerkuczewskiMichal/hw1.R
Labels: HW 1

#123 [HW2] Brochocki Mateusz
  homeworks/hw2/BrochockiMateusz/[HW2]BrochockiMateusz.R
Labels: HW 2

#124 [HW2] Ovcharenko Oleksandra
  homeworks/hw2/OvcharenkoOleksandra/HW2.R
Labels: HW 2

#126 [HW2] DebskiMichal
  homeworks/hw2/DebskiMichal/[HW2] DebskiMichal.R
Labels: HW 2

#127 [HW2] Luczkiewicz Izabela
  homeworks/hw2/LuczkiewiczIzabela/HW2.R
Labels: HW 2

#129 [HW2] Karch Aleksander
  homeworks/hw2/KarchAleksander/nie róbcie mi pullbacka z pull requesta.R
Labels: HW 2

#132 [HW2] Turczynski Maciej
  homeworks/hw2/TurczynskiMaciej/HW2.R
Labels: HW 2

#133 [HW2] Oliwia Wojtkowiak
  homeworks/hw2/WojtkowiakOliwia/HW2_Oliwia_Wojtkowiak.R
Labels: HW 2

#135 [HW2] Bartosz Szymanski
  homeworks/hw2/SzymanskiBartosz/HW2.R
Labels: HW 2

#137 [HW2] Baginski Kacper
  homeworks/hw2/BaginskiKacper/[HW2] Baginski Kacper.R
Labels: HW 2

#138 [HW2] Uznańska Aleksandra
  homeworks/hw2/HW2.R
  homeworks/hw2/UznanskaAleksandra/HW2.R
  homeworks/hw2/UznanskaAleksandra/README.md
  homeworks/hw2/UznanskaAleksandra/spotify-2023.csv
Labels: HW 2

#139 [HW2] Krzyzanowski Adrian
  homeworks/hw2/KrzyzanowskiAdrian/HW2.R
Labels: HW 2

#140 [HW2] Wyszomierski Łukasz
  homeworks/hw2/WyszomierskiLukasz/HW2.R
Labels: HW 2

#141 [HW2] Galat Julia
  homeworks/hw2/GalatJulia/HW2-Gałat-Julia.r
Labels: HW 2

#142 [HW2] Balcerzak Marta
  homeworks/hw2/BalcerzakMarta/HW2.R
Labels: HW 2

#143 [HW2] Koczorowski Maciej
  homeworks/hw2/KoczorowskiMaciej/HW2.R
Labels: HW 2

#144 [HW2] Zebialowicz Alicja
  homeworks/hw2/ZebialowiczAlicja/[HW2]ZebialowiczAlicja.R
Labels: HW 2

#145 [HW2] Idczak Aleksandra
  homeworks/hw2/IdczakAleksandra/HW2.R
Labels: HW 2

#146 [HW2] Strzelczyk Julia
  homeworks/hw2/StrzelczykJulia/HW2.R
Labels: HW 2

#147 [HW2] Ryll Mikolaj
  homeworks/hw2/RyllMikolaj/HW2.R
  homeworks/hw2/RyllMikolaj/images/2013.jpg
  homeworks/hw2/RyllMikolaj/images/2014.jpg
  homeworks/hw2/RyllMikolaj/images/2015.jpg
  homeworks/hw2/RyllMikolaj/images/2016.jpg
  homeworks/hw2/RyllMikolaj/images/2017.jpg
  homeworks/hw2/RyllMikolaj/images/2018.jpg
  homeworks/hw2/RyllMikolaj/images/2019.jpg
  homeworks/hw2/RyllMikolaj/images/2020.jpg
  homeworks/hw2/RyllMikolaj/images/2021.jpg
  homeworks/hw2/RyllMikolaj/images/2022.jpg
  homeworks/hw2/RyllMikolaj/images/2023.jpg
  homeworks/hw2/RyllMikolaj/spotify-2023.csv
Labels: HW 2

#148 [HW2] Pres Ewelina
  homeworks/hw2/PresEwelina/HW2.r
Labels: HW 2

#151 [HW2] Wojciechowski Maksymilian
  homeworks/hw2/WojciechowskiMaksymilian/HW2.R
Labels: HW 2

#152 [HW2] Franciszek Saliński
  homeworks/hw2/SalinskiFranciszek/HW2.R
Labels: HW 2

#153 [HW2] Maczka Marek
  homeworks/hw2/MaczkaMarek/[HW2] Maczka Marek.R
Labels: HW 2

#154 [HW2] Krawiec Krzysztof
  homeworks/hw2/KrawiecKrzysztof/HW2.R
Labels: HW 2

#155 [HW2] Cholewinski Kacper
  homeworks/hw2/CholewinskiKacper/HW2.R
Labels: HW 2

#156 [HW2] Krawczyk Maria
  homeworks/hw2/KrawczykMaria/HW2.R
Labels: HW 2

#157 [HW2] Tabian Maksymilian
  homeworks/hw2/TabianMaksymilian/HW2.R
Labels: HW 2

#159 [HW2] Orzechowska Weronika
  homeworks/hw2/OrzechowskaWeronika/HW2.R
Labels: HW 2

#160 [HW2] Lechoszest Igor
  homeworks/hw2/LechoszestIgor/HW2.R
Labels: HW 2

#161 [HW2] Bartosiewicz Piotr
  homeworks/hw2/BartosiewiczPiotr/pd2.R
Labels: HW 2

#162 [HW2] WolczykMichal
  homeworks/hw2/WolczykMichal/HW2.R
Labels: HW 2

#163 [HW2] Guttman Jan
  homeworks/hw2/GuttmanJan/[HW2]GuttmanJan.R
Labels: HW 2

#164 [HW2] Kowalski Paweł
  homeworks/hw2/KowalskiPawel/HW2.R
Labels: HW 2

#165 [HW2] LipinskaMalgorzata
  homeworks/hw2/LipinskaMalgorzata/HW2.R
Labels: HW 2

#168 [HW2] Pokora Bartosz
  homeworks/hw2/PokoraBartosz/HW2.R
Labels: HW 2

#169 [PD2] Gromada Patrycja
  homeworks/hw2/GromadaPatrycja/HW2 PG.R
Labels: HW 2

#170 [HW2] Gajda Natalia
  homeworks/hw2/GajdaNatalia/HW2.R
Labels: HW 2

#171 [HW2] Podbielski Bruno
  homeworks/hw2/PodbielskiBruno/HW2.R
Labels: HW 2

#174 [HW2] Serkuczewski Michał
  homeworks/hw2/SerkuczewskiMichal/hw2.R
  homeworks/hw2/SerkuczewskiMichal/hw2.Rproj
  homeworks/hw2/SerkuczewskiMichal/spotify-2023.csv
Labels: HW 2

#175 HW2_Sien_Magdalena
  homeworks/hw2/SienMagdalena/HW2.R
Labels: HW 2

#176 PokropekDaniel
  homeworks/hw2/PokropekDaniel/PokropekDaniel.R
Labels: HW 2

#179 [HW2] Krzysztof Maślak
  homeworks/hw2/MaslakKrzysztof/[HW2] Maślak Krzysztof.R
Labels: HW 2

#178 [HW2] Michna Jakub
  homeworks/hw2/MichnaJakub/MichnaJakub.R
  projects/project1/nazwisko1_nazwisko2_nazwisko3/kody/README.md
Labels: HW 2

#180 [HW2]KiszkaMateusz
  homeworks/hw2/KiszkaMateusz/HW2.R
Labels: HW 2

#167 [HW2] ZajacKarolina
  homeworks/hw2/ZajacKarolina/HW2 (1).R
Labels: fixes needed 🛠️, HW 2
